This is success with cypress
Polyakovst/TestProject1 pull request #4
Opened 2022-07-25 14:44 UTC by Polyakovst

2022-08-02 17:52 UTC, anatoly-devico reviewed
push cypress.config.js file to github

2022-08-02 17:55 UTC, anatoly-devico requested changes

2022-08-02 17:55 UTC, anatoly-devico commented on cypress/selectors/bank_account_screen.js
> +    //Locators for elements on the bank accounts screen
useless comment

2022-08-02 17:55 UTC, anatoly-devico commented on cypress/selectors/main_screen.js
> +    //Locators for elements on the main screen
useless comment

2022-08-02 17:55 UTC, anatoly-devico commented on cypress/selectors/sign_up_page.js
> +    //Locators for elements on the 'sign up' page
useless comment

2022-08-02 17:55 UTC, anatoly-devico commented on cypress/selectors/transaction_creation_screen.js
> +    //Locators for elements on the new transaction creation screen
useless comment

2022-08-02 17:55 UTC, anatoly-devico commented on cypress/selectors/transactions_screen.js
> +    //Locators for elements on transactions screen
useless comment

2022-08-02 17:55 UTC, anatoly-devico commented on cypress/support/commands.js
> +// Cypress.Commands.add('login', (email, password) => { ... })
Remove unused commented lines

2022-08-03 15:15 UTC, Polyakovst commented on cypress/selectors/bank_account_screen.js
> +    //Locators for elements on the bank accounts screen
Comment removed

2022-08-03 15:15 UTC, Polyakovst commented on cypress/selectors/main_screen.js
> +    //Locators for elements on the main screen
Comment removed

2022-08-03 15:15 UTC, Polyakovst commented on cypress/selectors/sign_up_page.js
> +    //Locators for elements on the 'sign up' page
Comment removed

2022-08-03 15:15 UTC, Polyakovst commented on cypress/selectors/transaction_creation_screen.js
> +    //Locators for elements on the new transaction creation screen
Comment removed

2022-08-03 15:15 UTC, Polyakovst commented on cypress/selectors/transactions_screen.js
> +    //Locators for elements on transactions screen
Comment removed

2022-08-03 15:16 UTC, Polyakovst commented on cypress/support/commands.js
> +// Cypress.Commands.add('login', (email, password) => { ... })
All unused comments removed

2022-08-03 15:17 UTC, Polyakovst commented
> push cypress.config.js file to github

cypress.config.сjs file pushed to github

2022-08-04 15:20 UTC, anatoly-devico approved these changes
Approved

2022-08-04 17:45 UTC, merged